### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by rvantonder** [uber/NEAL#8]
When running `make`, this gets run:
```
make -C docs build
python -msphinx -M build "." "_build"  
```
and fails:
```
Running Sphinx v1.6.4

Sphinx error:
Builder name build not registered or available through entry point
```
Catch-all on this line is causing it https://github.com/uber/NEAL/blob/master/docs/Makefile#L20

**Comment by tadeuzagallo** [comment]
I believe this was due to the greedy rule in `Makefile.propagate`, that automatically repeats the command on every folder that has a `Makefile`. It should have been fixed on 9e172e5e3519539c5a6ffcc8383b6e3c6f78bb36 (see diff [here](https://github.com/uber/NEAL/commit/9e172e5e3519539c5a6ffcc8383b6e3c6f78bb36#diff-bd5fdd116c7207178b05c6918829d593)). Can you confirm if you still see the error after this commit?
